# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' @param df A data frame or data table
#' @param by_col group by column
#' @importFrom data.table setDT
#' @return a Data Frame
#' 
#' @export
#' @examples
#' data("iris")
#' my_summary(df = iris,
#'            by = "Species")
my_summary <- function(df, by_col){
    
  if(isFALSE(inherits(df, "data.table"))){
    
    setDT(df)
  }
  
  df2 = df[, lapply(.SD, mean), by = by_col]
  df2
}
