# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' @param df A data frame 
#' @param x, x axis value
#' @param y y axis value
#' @param col_var color variable value
#' @return a list of class ggplot
#' @importFrom ggplot2 ggplot 
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 theme_minimal
#' @export
#' @examples
#' myScatter(df = iris_data,
#'           x = Petal.Width , 
#'           y = Petal.Length , 
#'           col_var = Species)
myScatter <- function(df, x, y, col_var = NULL){
  
  ggplot(df, aes(x = {{x}},  y = {{y}}, color = {{col_var}}))+
    geom_point()+
    theme_minimal()
}

